In [2]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn import linear_model

Data = pd.read_csv('D:/Python/File Handling/LogistRegress.csv')
Data
label = LabelEncoder()
Data['Insurance'] = label.fit_transform(Data['Insurance'])
Data

    Age  Insurance
0    22          0
1    25          0
2    47          1
3    52          0
4    46          1
5    56          1
6    55          0
7    60          2
8    62          1
9    61          1
10   18          0
11   28          0
12   27          0
13   29          0
14   49          1
15   55          1
16   25          1
17   58          1
18   19          0
19   18          0
20   21          0
21   26          0
22   40          1
23   45          1
24   50          1
25   54          1
26   23          0

In [3]:
X = Data[['Age']]
Y = Data['Insurance']

Model = linear_model.LogisticRegression()

Xtr , Yts , Ytr , Yts = train_test_split(X,Y,test_size=0.2)

Model.fit(Xtr,Ytr)
Model.score(Xtr,Ytr)
Xtr

    Age
25   54
13   29
4    46
0    22
8    62
20   21
11   28
12   27
6    55
17   58
16   25
18   19
3    52
15   55
9    61
7    60
22   40
5    56
24   50
23   45
1    25

In [7]:
print('0 Indicates No will Buy Insurence')
print('1 Indicates Will Buy Insurence')
Model.predict([[54]])

0 Indicates No will Buy Insurence
1 Indicates Will Buy Insurence

C:\Users\Shree\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([1])

In [44]:
import pandas
import matplotlib.pyplot as plt
from sklearn import linear_model
import numpy
Data = pandas.read_csv('D:/Python/File Handling/MultiRegress.csv')
print(Data.head())

          Car       Model  Volume  Weight  CO2
0      Toyoty        Aygo    1000     790   99
1  Mitsubishi  Space Star    1200    1160   95
2       Skoda      Citigo    1000     929   95
3        Fiat         500     900     865   90
4        Mini      Cooper    1500    1140  105

In [49]:
X = Data[['Volume','Weight']]
Y = Data['CO2']
Mul_model = linear_model.LinearRegression()
Mul_model.fit(X,Y)

Volume = int(input('\nEnter the Volume :'))
Weight = int(input('\nEnter the Weight :'))
Predict = Mul_model.predict([[Volume,Weight]])
Predict

C:\Users\Shree\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([138.59134173])